# fly.toml app configuration file generated for finch-collector-kb on 2024-06-05T12:56:57-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'finch-collector-kb'
primary_region = 'ord'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
